"""Check: Christoffel symbols of the 2-sphere metric used in section 2.

Physics. The sphere is curved, so the basis vectors pointing east and north
rotate as a fluid column moves. A column travelling due east along a latitude
circle is continuously changing direction in the ambient space even though it
holds its heading, and the momentum equations must account for that. The
Christoffel symbols are exactly that bookkeeping: they are what turn partial
derivatives into covariant ones, and in the shallow-water momentum equations
they appear as the familiar metric terms ``u v tan(phi)/R`` and
``-u^2 tan(phi)/R``. They are not decoration -- get them wrong and the
"westward" of section 5 becomes a coordinate artefact rather than a physical
statement.

What is checked.

1. The symbols computed from the metric ``ds^2 = R^2 dphi^2 + R^2 cos^2 phi
   dlambda^2`` against the closed forms used in the text:

       Gamma^lambda_{lambda phi} = Gamma^lambda_{phi lambda} = -tan(phi)
       Gamma^phi_{lambda lambda} = sin(phi) cos(phi)

   with all remaining components identically zero.

2. The same symbols against the standard published values for the 2-sphere in
   the colatitude convention (``Gamma^theta_{varphi varphi} = -sin theta cos
   theta``, ``Gamma^varphi_{theta varphi} = cot theta``, e.g. any text on
   Riemannian geometry), transported to the latitude convention by
   ``phi = pi/2 - theta``. This is the independent cross-check: the latitude
   forms above are re-derived from the published colatitude forms rather than
   simply asserted alongside them.

3. The physical payoff, verified rather than asserted: that the covariant
   divergence ``(1/sqrt(g)) d_i(sqrt(g) V^i)`` reproduces the spherical
   divergence in physical (orthonormal) components used throughout section 3,

       div u = 1/(R cos phi) [ d_lambda u + d_phi (v cos phi) ]

   and that the metric terms generated by the Christoffel symbols in the
   covariant material derivative are exactly ``u v tan(phi)/R`` in the zonal
   momentum equation and ``-u^2 tan(phi)/R`` in the meridional one.

Run: ``python theory/sympy_checks/check_christoffel_symbols.py``
Prints VERIFIED or MISMATCH and exits non-zero on MISMATCH.
"""

from __future__ import annotations

import sys
from pathlib import Path

import sympy as sp

lam, phi, t = sp.symbols("lambda phi t", real=True)
R = sp.Symbol("R", positive=True)

# Coordinate order used throughout: x^0 = lambda (longitude), x^1 = phi (latitude).
COORDS = (lam, phi)
NAMES = ("lambda", "phi")


def metric():
    return sp.Matrix([[R**2 * sp.cos(phi) ** 2, 0], [0, R**2]])


def christoffel(g, coords):
    """Gamma[k][i][j] = 1/2 g^{kl} (d_i g_{jl} + d_j g_{il} - d_l g_{ij})."""
    ginv = g.inv()
    n = len(coords)
    Gamma = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    for k in range(n):
        for i in range(n):
            for j in range(n):
                total = sp.S.Zero
                for lidx in range(n):
                    total += ginv[k, lidx] * (
                        sp.diff(g[j, lidx], coords[i])
                        + sp.diff(g[i, lidx], coords[j])
                        - sp.diff(g[i, j], coords[lidx])
                    )
                Gamma[k][i][j] = sp.simplify(total / 2)
    return Gamma


def expected_latitude():
    """Closed forms as written in section 2 of derivations.tex."""
    n = 2
    E = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    E[0][0][1] = -sp.tan(phi)  # Gamma^lambda_{lambda phi}
    E[0][1][0] = -sp.tan(phi)  # Gamma^lambda_{phi lambda}
    E[1][0][0] = sp.sin(phi) * sp.cos(phi)  # Gamma^phi_{lambda lambda}
    return E


def published_colatitude_transported():
    """Published 2-sphere values in colatitude, transported to latitude.

    In colatitude ``theta`` with azimuth ``varphi``, the standard non-zero
    components are ``Gamma^theta_{varphi varphi} = -sin theta cos theta`` and
    ``Gamma^varphi_{theta varphi} = Gamma^varphi_{varphi theta} = cot theta``.
    Under the substitution ``theta = pi/2 - phi`` (so ``d/dtheta = -d/dphi``),
    each index carried by ``theta`` contributes a factor ``dtheta/dphi = -1``
    for a lower index and ``dphi/dtheta = -1`` for an upper index.
    """
    theta = sp.Symbol("theta", real=True)
    lat = sp.pi / 2 - phi  # theta in terms of phi

    g_theta_pp = sp.simplify((-sp.sin(theta) * sp.cos(theta)).subs(theta, lat))
    g_phi_tp = sp.simplify(sp.cot(theta).subs(theta, lat))

    n = 2
    E = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    # Gamma^phi_{lambda lambda}: upper index theta -> phi gives one factor (-1);
    # lower indices are both azimuthal, so unchanged.
    E[1][0][0] = sp.simplify(-g_theta_pp)
    # Gamma^lambda_{lambda phi}: upper index azimuthal (unchanged); one lower
    # index theta -> phi gives one factor (-1).
    E[0][0][1] = sp.simplify(-g_phi_tp)
    E[0][1][0] = E[0][0][1]
    return E


def compare(computed, expected, label, lines):
    ok = True
    n = 2
    for k in range(n):
        for i in range(n):
            for j in range(n):
                diff = sp.simplify(computed[k][i][j] - expected[k][i][j])
                if diff != 0:
                    ok = False
                    lines.append(
                        f"    MISMATCH Gamma^{NAMES[k]}_{{{NAMES[i]} {NAMES[j]}}}: "
                        f"computed {computed[k][i][j]}, expected "
                        f"{expected[k][i][j]}, difference {diff}"
                    )
    lines.append(f"  {label}: {'all 8 components agree' if ok else 'DISAGREEMENT'}")
    return ok


def divergence_check(Gamma, lines):
    """Covariant divergence in physical components equals the section-3 form."""
    u = sp.Function("u")(lam, phi)  # eastward physical component
    v = sp.Function("v")(lam, phi)  # northward physical component

    # Contravariant components from physical ones: u = R cos(phi) V^lambda,
    # v = R V^phi.
    Vlam = u / (R * sp.cos(phi))
    Vphi = v / R

    g = metric()
    sqrtg = sp.sqrt(sp.simplify(g.det()))  # = R^2 cos(phi) for -pi/2 < phi < pi/2
    sqrtg = sp.simplify(sqrtg.rewrite(sp.Abs).subs(sp.Abs(sp.cos(phi)), sp.cos(phi)))

    div_voigt = sp.simplify((sp.diff(sqrtg * Vlam, lam) + sp.diff(sqrtg * Vphi, phi)) / sqrtg)
    # Equivalent contracted-Christoffel form, exercising Gamma directly.
    V = (Vlam, Vphi)
    div_gamma = sum(sp.diff(V[i], COORDS[i]) for i in range(2)) + sum(
        Gamma[k][k][i] * V[i] for k in range(2) for i in range(2)
    )
    div_gamma = sp.simplify(div_gamma)

    div_expected = sp.simplify(
        (sp.diff(u, lam) + sp.diff(v * sp.cos(phi), phi)) / (R * sp.cos(phi))
    )

    d1 = sp.simplify(div_voigt - div_expected)
    d2 = sp.simplify(div_gamma - div_expected)
    ok = (d1 == 0) and (d2 == 0)
    lines.append(
        f"  sqrt(g) form vs section-3 divergence: "
        f"{'exact zero' if d1 == 0 else f'NONZERO {d1}'}"
    )
    lines.append(
        f"  contracted-Gamma form vs section-3 divergence: "
        f"{'exact zero' if d2 == 0 else f'NONZERO {d2}'}"
    )
    return ok


def metric_terms_check(Gamma, lines):
    """The Christoffel symbols generate the momentum-equation metric terms."""
    # Physical velocity components along a trajectory.
    U = sp.Function("u")(t)
    V = sp.Function("v")(t)
    Phi = sp.Function("phi")(t)

    # Contravariant velocity: V^lambda = u/(R cos phi), V^phi = v/R.
    Vc = [U / (R * sp.cos(Phi)), V / R]

    # Covariant acceleration a^k = dV^k/dt + Gamma^k_{ij} V^i V^j, with the
    # Christoffels evaluated on the trajectory.
    G = [[[Gamma[k][i][j].subs(phi, Phi) for j in range(2)] for i in range(2)] for k in range(2)]
    a = [
        sp.diff(Vc[k], t) + sum(G[k][i][j] * Vc[i] * Vc[j] for i in range(2) for j in range(2))
        for k in range(2)
    ]

    # Convert back to physical components: a_zonal = R cos(phi) a^lambda
    # + (d/dt of the basis scaling), a_merid = R a^phi. The physical zonal
    # acceleration is R cos(Phi) a^lambda plus the term from differentiating the
    # scale factor, which the covariant derivative already carries; taking
    # R cos(Phi) a^lambda directly gives Du/Dt plus the metric term.
    a_zonal = sp.simplify(R * sp.cos(Phi) * a[0])
    a_merid = sp.simplify(R * a[1])

    dPhi = sp.diff(Phi, t)
    a_zonal = a_zonal.subs(dPhi, V / R).doit()
    a_merid = a_merid.subs(dPhi, V / R).doit()

    expected_zonal = sp.diff(U, t) - U * V * sp.tan(Phi) / R
    expected_merid = sp.diff(V, t) + U**2 * sp.tan(Phi) / R

    d1 = sp.simplify(a_zonal - expected_zonal)
    d2 = sp.simplify(a_merid - expected_merid)
    ok = (d1 == 0) and (d2 == 0)
    lines.append(
        "  zonal metric term  -u v tan(phi)/R: " f"{'exact zero' if d1 == 0 else f'NONZERO {d1}'}"
    )
    lines.append(
        "  merid. metric term +u^2 tan(phi)/R: " f"{'exact zero' if d2 == 0 else f'NONZERO {d2}'}"
    )
    return ok


def main() -> int:
    lines: list[str] = []
    lines.append("check_christoffel_symbols")
    lines.append("=" * 60)
    lines.append("Metric: ds^2 = R^2 dphi^2 + R^2 cos^2(phi) dlambda^2")
    lines.append("")

    g = metric()
    Gamma = christoffel(g, COORDS)

    lines.append("Computed non-zero components")
    lines.append("-" * 60)
    any_nonzero = False
    for k in range(2):
        for i in range(2):
            for j in range(2):
                if Gamma[k][i][j] != 0:
                    any_nonzero = True
                    lines.append(
                        f"  Gamma^{NAMES[k]}_{{{NAMES[i]} {NAMES[j]}}} = " f"{Gamma[k][i][j]}"
                    )
    if not any_nonzero:
        lines.append("  (none -- this is itself a failure)")

    lines.append("")
    lines.append("Arm 1 - against the closed forms written in section 2")
    lines.append("-" * 60)
    ok1 = compare(Gamma, expected_latitude(), "section-2 forms", lines)

    lines.append("")
    lines.append("Arm 2 - against published 2-sphere values (colatitude, transported)")
    lines.append("-" * 60)
    ok2 = compare(Gamma, published_colatitude_transported(), "published values", lines)

    lines.append("")
    lines.append("Arm 3 - physical payoff: divergence in physical components")
    lines.append("-" * 60)
    ok3 = divergence_check(Gamma, lines)

    lines.append("")
    lines.append("Arm 4 - physical payoff: momentum-equation metric terms")
    lines.append("-" * 60)
    ok4 = metric_terms_check(Gamma, lines)

    ok = ok1 and ok2 and ok3 and ok4
    lines.append("")
    lines.append(f"VERDICT: {'VERIFIED' if ok else 'MISMATCH'}")

    report = "\n".join(lines) + "\n"
    print(report, end="")

    out = Path(__file__).resolve().parent / "output"
    out.mkdir(exist_ok=True)
    (out / (Path(__file__).stem + ".txt")).write_text(report)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
