"""Check: Christoffel symbols of the 2-sphere metric used in section 2.

Physics. The sphere is curved, so the basis vectors pointing east and north
rotate as a fluid column moves. A column travelling due east along a latitude
circle is continuously changing direction in the ambient space even though it
holds its heading, and the momentum equations must account for that. The
Christoffel symbols are exactly that bookkeeping: they are what turn partial
derivatives into covariant ones, and in the shallow-water momentum equations
they appear as the familiar metric terms ``u v tan(phi)/R`` and
``-u^2 tan(phi)/R``. They are not decoration -- get them wrong and the
"westward" of section 5 becomes a coordinate artefact rather than a physical
statement.

What is checked.

1. The symbols computed from the metric ``ds^2 = R^2 dphi^2 + R^2 cos^2 phi
   dlambda^2`` against the closed forms used in the text:

       Gamma^lambda_{lambda phi} = Gamma^lambda_{phi lambda} = -tan(phi)
       Gamma^phi_{lambda lambda} = sin(phi) cos(phi)

   with all remaining components identically zero.

2. The same symbols against an *independent recomputation* in the colatitude
   chart. The colatitude metric ``ds^2 = R^2 dtheta^2 + R^2 sin^2(theta)
   dvarphi^2`` is built from scratch, the same Christoffel formula is run on it,
   and the result is transported into the latitude chart by the tensor
   transformation law under ``theta = pi/2 - phi``. Two independent computations
   in two charts must agree afterwards. Nothing is quoted from any source.

3. The Gaussian curvature implied by the computed connection, which must be
   ``1/R^2`` for a sphere of radius ``R``. A wrong connection cannot reproduce
   the curvature of the manifold it is supposed to describe, so this closes the
   loop internally rather than against a publication.

4. The physical payoff, verified rather than asserted: that the covariant
   divergence ``(1/sqrt(g)) d_i(sqrt(g) V^i)`` reproduces the spherical
   divergence in physical (orthonormal) components used throughout section 3,

       div u = 1/(R cos phi) [ d_lambda u + d_phi (v cos phi) ]

   and that the metric terms generated by the Christoffel symbols in the
   covariant material derivative are exactly ``u v tan(phi)/R`` in the zonal
   momentum equation and ``-u^2 tan(phi)/R`` in the meridional one.

Run: ``python theory/sympy_checks/check_christoffel_symbols.py``
Prints VERIFIED or MISMATCH and exits non-zero on MISMATCH.
"""

from __future__ import annotations

import sys
from pathlib import Path

import sympy as sp

lam, phi, t = sp.symbols("lambda phi t", real=True)
R = sp.Symbol("R", positive=True)

# Coordinate order used throughout: x^0 = lambda (longitude), x^1 = phi (latitude).
COORDS = (lam, phi)
NAMES = ("lambda", "phi")


def metric():
    return sp.Matrix([[R**2 * sp.cos(phi) ** 2, 0], [0, R**2]])


def christoffel(g, coords):
    """Gamma[k][i][j] = 1/2 g^{kl} (d_i g_{jl} + d_j g_{il} - d_l g_{ij})."""
    ginv = g.inv()
    n = len(coords)
    Gamma = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    for k in range(n):
        for i in range(n):
            for j in range(n):
                total = sp.S.Zero
                for lidx in range(n):
                    total += ginv[k, lidx] * (
                        sp.diff(g[j, lidx], coords[i])
                        + sp.diff(g[i, lidx], coords[j])
                        - sp.diff(g[i, j], coords[lidx])
                    )
                Gamma[k][i][j] = sp.simplify(total / 2)
    return Gamma


def expected_latitude():
    """Closed forms as written in section 2 of derivations.tex."""
    n = 2
    E = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    E[0][0][1] = -sp.tan(phi)  # Gamma^lambda_{lambda phi}
    E[0][1][0] = -sp.tan(phi)  # Gamma^lambda_{phi lambda}
    E[1][0][0] = sp.sin(phi) * sp.cos(phi)  # Gamma^phi_{lambda lambda}
    return E


def colatitude_recomputed_and_transported():
    """Recompute in colatitude from its own metric, then transport to latitude.

    This arm quotes nothing. It builds the colatitude metric
    ``ds^2 = R^2 dtheta^2 + R^2 sin^2(theta) dvarphi^2`` independently, runs the
    same Christoffel formula on it, and then transports the result into the
    latitude chart by the tensor transformation law under ``theta = pi/2 - phi``.
    Two independent computations in two different charts must agree after the
    transformation, so this is a genuine consistency check on the connection and
    on the handling of the convention, with no external source involved.

    (An earlier version of this script instead compared against colatitude values
    written down from general familiarity and labelled "published values". That
    was an unattributed claim of the kind this project's provenance rule exists
    to prevent, and it has been replaced by the computation above. See
    theory/PROVENANCE_AUDIT.md.)
    """
    theta, varphi = sp.symbols("theta varphi", real=True)
    g_co = sp.Matrix([[R**2, 0], [0, R**2 * sp.sin(theta) ** 2]])
    G_co = christoffel(g_co, (theta, varphi))  # indices ordered (theta, varphi)

    # Transport to (lambda, phi) with lambda = varphi, phi = pi/2 - theta. The
    # Jacobian is diagonal and constant: d(theta)/d(phi) = -1, d(varphi)/d(lambda) = 1.
    # With coordinate order (lambda, phi) here and (theta, varphi) there, the
    # index map is 0 <-> varphi(1), 1 <-> theta(0), with a sign on every theta index.
    idx = {0: 1, 1: 0}  # latitude-chart index -> colatitude-chart index
    sgn = {0: 1, 1: -1}  # sign carried by that index under the transformation

    n = 2
    E = [[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)]
    for k in range(n):
        for i in range(n):
            for j in range(n):
                # Upper index transforms with dx^k/dy, lower indices with dy/dx.
                factor = sgn[k] * sgn[i] * sgn[j]
                val = G_co[idx[k]][idx[i]][idx[j]]
                E[k][i][j] = sp.simplify((factor * val).subs(theta, sp.pi / 2 - phi))
    return E


def curvature_check(Gamma, lines):
    """Independent confirmation: the connection must give Gaussian curvature 1/R^2.

    A wrong connection would not reproduce the curvature of a sphere of radius R,
    so this closes the loop without appealing to any external source at all.
    """
    n = 2
    # Riemann tensor R^rho_{sigma mu nu} from the Christoffel symbols.
    Riem = [[[[sp.S.Zero] * n for _ in range(n)] for _ in range(n)] for _ in range(n)]
    for r in range(n):
        for s in range(n):
            for mu in range(n):
                for nu in range(n):
                    expr = sp.diff(Gamma[r][nu][s], COORDS[mu]) - sp.diff(
                        Gamma[r][mu][s], COORDS[nu]
                    )
                    for lm in range(n):
                        expr += (
                            Gamma[r][mu][lm] * Gamma[lm][nu][s]
                            - Gamma[r][nu][lm] * Gamma[lm][mu][s]
                        )
                    Riem[r][s][mu][nu] = sp.simplify(expr)

    g = metric()
    ginv = g.inv()
    # Ricci scalar, then Gaussian curvature K = Ricci/2 in two dimensions.
    ricci = [[sp.S.Zero] * n for _ in range(n)]
    for s in range(n):
        for nu in range(n):
            ricci[s][nu] = sp.simplify(sum(Riem[r][s][r][nu] for r in range(n)))
    scalar = sum(ginv[s, nu] * ricci[s][nu] for s in range(n) for nu in range(n))

    # Rewrite tan as sin/cos before simplifying: sympy's simplify does not
    # reduce (sin(2p)tan(p) + 3cos(2p) + 1)/(4cos^2 p) to 1 while the tangent
    # is still present, and would otherwise leave a true identity looking false.
    def _tidy(expr):
        expr = expr.subs(sp.tan(phi), sp.sin(phi) / sp.cos(phi))
        return sp.simplify(sp.trigsimp(sp.expand_trig(expr)))

    scalar = _tidy(scalar)
    K = _tidy(scalar / 2)
    ok = _tidy(K - 1 / R**2) == 0
    lines.append(f"  Ricci scalar from the computed connection: {scalar}")
    lines.append(
        f"  Gaussian curvature K = R_scalar/2 = {K}, expected 1/R^2: "
        f"{'agrees' if ok else 'DISAGREES'}"
    )
    lines.append("  A wrong connection could not reproduce the curvature of a sphere of")
    lines.append("  radius R, so this confirms the symbols with no source quoted.")
    return ok


def compare(computed, expected, label, lines):
    ok = True
    n = 2
    for k in range(n):
        for i in range(n):
            for j in range(n):
                diff = sp.simplify(computed[k][i][j] - expected[k][i][j])
                if diff != 0:
                    ok = False
                    lines.append(
                        f"    MISMATCH Gamma^{NAMES[k]}_{{{NAMES[i]} {NAMES[j]}}}: "
                        f"computed {computed[k][i][j]}, expected "
                        f"{expected[k][i][j]}, difference {diff}"
                    )
    lines.append(f"  {label}: {'all 8 components agree' if ok else 'DISAGREEMENT'}")
    return ok


def divergence_check(Gamma, lines):
    """Covariant divergence in physical components equals the section-3 form."""
    u = sp.Function("u")(lam, phi)  # eastward physical component
    v = sp.Function("v")(lam, phi)  # northward physical component

    # Contravariant components from physical ones: u = R cos(phi) V^lambda,
    # v = R V^phi.
    Vlam = u / (R * sp.cos(phi))
    Vphi = v / R

    g = metric()
    sqrtg = sp.sqrt(sp.simplify(g.det()))  # = R^2 cos(phi) for -pi/2 < phi < pi/2
    sqrtg = sp.simplify(sqrtg.rewrite(sp.Abs).subs(sp.Abs(sp.cos(phi)), sp.cos(phi)))

    div_voigt = sp.simplify((sp.diff(sqrtg * Vlam, lam) + sp.diff(sqrtg * Vphi, phi)) / sqrtg)
    # Equivalent contracted-Christoffel form, exercising Gamma directly.
    V = (Vlam, Vphi)
    div_gamma = sum(sp.diff(V[i], COORDS[i]) for i in range(2)) + sum(
        Gamma[k][k][i] * V[i] for k in range(2) for i in range(2)
    )
    div_gamma = sp.simplify(div_gamma)

    div_expected = sp.simplify(
        (sp.diff(u, lam) + sp.diff(v * sp.cos(phi), phi)) / (R * sp.cos(phi))
    )

    d1 = sp.simplify(div_voigt - div_expected)
    d2 = sp.simplify(div_gamma - div_expected)
    ok = (d1 == 0) and (d2 == 0)
    lines.append(
        f"  sqrt(g) form vs section-3 divergence: "
        f"{'exact zero' if d1 == 0 else f'NONZERO {d1}'}"
    )
    lines.append(
        f"  contracted-Gamma form vs section-3 divergence: "
        f"{'exact zero' if d2 == 0 else f'NONZERO {d2}'}"
    )
    return ok


def metric_terms_check(Gamma, lines):
    """The Christoffel symbols generate the momentum-equation metric terms."""
    # Physical velocity components along a trajectory.
    U = sp.Function("u")(t)
    V = sp.Function("v")(t)
    Phi = sp.Function("phi")(t)

    # Contravariant velocity: V^lambda = u/(R cos phi), V^phi = v/R.
    Vc = [U / (R * sp.cos(Phi)), V / R]

    # Covariant acceleration a^k = dV^k/dt + Gamma^k_{ij} V^i V^j, with the
    # Christoffels evaluated on the trajectory.
    G = [[[Gamma[k][i][j].subs(phi, Phi) for j in range(2)] for i in range(2)] for k in range(2)]
    a = [
        sp.diff(Vc[k], t) + sum(G[k][i][j] * Vc[i] * Vc[j] for i in range(2) for j in range(2))
        for k in range(2)
    ]

    # Convert back to physical components: a_zonal = R cos(phi) a^lambda
    # + (d/dt of the basis scaling), a_merid = R a^phi. The physical zonal
    # acceleration is R cos(Phi) a^lambda plus the term from differentiating the
    # scale factor, which the covariant derivative already carries; taking
    # R cos(Phi) a^lambda directly gives Du/Dt plus the metric term.
    a_zonal = sp.simplify(R * sp.cos(Phi) * a[0])
    a_merid = sp.simplify(R * a[1])

    dPhi = sp.diff(Phi, t)
    a_zonal = a_zonal.subs(dPhi, V / R).doit()
    a_merid = a_merid.subs(dPhi, V / R).doit()

    expected_zonal = sp.diff(U, t) - U * V * sp.tan(Phi) / R
    expected_merid = sp.diff(V, t) + U**2 * sp.tan(Phi) / R

    d1 = sp.simplify(a_zonal - expected_zonal)
    d2 = sp.simplify(a_merid - expected_merid)
    ok = (d1 == 0) and (d2 == 0)
    lines.append(
        "  zonal metric term  -u v tan(phi)/R: " f"{'exact zero' if d1 == 0 else f'NONZERO {d1}'}"
    )
    lines.append(
        "  merid. metric term +u^2 tan(phi)/R: " f"{'exact zero' if d2 == 0 else f'NONZERO {d2}'}"
    )
    return ok


def main() -> int:
    lines: list[str] = []
    lines.append("check_christoffel_symbols")
    lines.append("=" * 60)
    lines.append("Metric: ds^2 = R^2 dphi^2 + R^2 cos^2(phi) dlambda^2")
    lines.append("")

    g = metric()
    Gamma = christoffel(g, COORDS)

    lines.append("Computed non-zero components")
    lines.append("-" * 60)
    any_nonzero = False
    for k in range(2):
        for i in range(2):
            for j in range(2):
                if Gamma[k][i][j] != 0:
                    any_nonzero = True
                    lines.append(
                        f"  Gamma^{NAMES[k]}_{{{NAMES[i]} {NAMES[j]}}} = " f"{Gamma[k][i][j]}"
                    )
    if not any_nonzero:
        lines.append("  (none -- this is itself a failure)")

    lines.append("")
    lines.append("Arm 1 - against the closed forms written in section 2")
    lines.append("-" * 60)
    ok1 = compare(Gamma, expected_latitude(), "section-2 forms", lines)

    lines.append("")
    lines.append("Arm 2 - independent recomputation in the colatitude chart, transported")
    lines.append("-" * 60)
    ok2 = compare(Gamma, colatitude_recomputed_and_transported(), "colatitude recomputation", lines)

    lines.append("")
    lines.append("Arm 3 - Gaussian curvature implied by the connection")
    lines.append("-" * 60)
    ok3 = curvature_check(Gamma, lines)

    lines.append("")
    lines.append("Arm 4 - physical payoff: divergence in physical components")
    lines.append("-" * 60)
    ok4 = divergence_check(Gamma, lines)

    lines.append("")
    lines.append("Arm 5 - physical payoff: momentum-equation metric terms")
    lines.append("-" * 60)
    ok5 = metric_terms_check(Gamma, lines)

    ok = ok1 and ok2 and ok3 and ok4 and ok5
    lines.append("")
    lines.append(f"VERDICT: {'VERIFIED' if ok else 'MISMATCH'}")

    report = "\n".join(lines) + "\n"
    print(report, end="")

    out = Path(__file__).resolve().parent / "output"
    out.mkdir(exist_ok=True)
    (out / (Path(__file__).stem + ".txt")).write_text(report)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
